# Generated by Django 5.1.7 on 2025-05-04 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id_juego",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("plataforma", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=100)),
                ("desarrollador", models.CharField(blank=True, max_length=100)),
                ("publicador", models.CharField(blank=True, max_length=100)),
                ("fecha_lanzamiento", models.DateField(blank=True, null=True)),
                ("descripcion_corta", models.TextField(blank=True)),
                ("imagen_miniatura", models.URLField(blank=True)),
                ("url_juego", models.URLField(blank=True)),
                ("url_perfil", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConfigUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(blank=True, max_length=100)),
                (
                    "tipo_letra",
                    models.CharField(
                        choices=[
                            ("sans-serif", "Sans Serif"),
                            ("serif", "Serif"),
                            ("monospace", "Monospace"),
                        ],
                        default="sans-serif",
                        max_length=100,
                    ),
                ),
                (
                    "tamano_texto",
                    models.CharField(
                        choices=[
                            ("small", "Pequeño"),
                            ("medium", "Mediano"),
                            ("large", "Grande"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamerank.juego"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamerank.juego"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("juego", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voto",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamerank.juego"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("juego", "usuario")},
            },
        ),
    ]
