# Generated by Django 5.1.7 on 2025-05-06 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConfigUsuario",
            new_name="ConfiguracionUsuario",
        ),
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["fecha"]},
        ),
    ]
