# Generated by Django 5.1.7 on 2025-05-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0002_rename_configusuario_configuracionusuario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-fecha"]},
        ),
    ]
