# Generated by Django 5.1.7 on 2025-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0003_alter_comentario_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionusuario",
            name="tamano_texto",
            field=models.CharField(
                choices=[
                    ("tamano-small", "Pequeño"),
                    ("tamano-medium", "Mediano"),
                    ("tamano-large", "Grande"),
                    ("tamano-xl", "Extra grande"),
                ],
                default="tamano-medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionusuario",
            name="tipo_letra",
            field=models.CharField(
                choices=[
                    ("fuente-sans-serif", "Sans Serif (Rubik)"),
                    ("fuente-serif", "Serif (Roboto Slab)"),
                    ("fuente-monospace", "Monoespaciada (Fira Code)"),
                    ("fuente-decorativa", "Decorativa (Pacifico)"),
                ],
                default="fuente-sans-serif",
                max_length=30,
            ),
        ),
    ]
