# Generated by Django 5.1.7 on 2025-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0005_votocomentario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="juego",
            old_name="descripcion_corta",
            new_name="descripcion",
        ),
    ]
