# Generated by Django 5.1.7 on 2025-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0006_rename_descripcion_corta_juego_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContrasenaValida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contrasena", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="juego",
            old_name="descripcion",
            new_name="descripcion_corta",
        ),
    ]
