# Generated by Django 5.1.7 on 2025-05-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamerank", "0007_contrasenavalida_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContrasenaValida",
        ),
    ]
